### ISSUE TITLE
Using a ":" in items makes ChoiceTableGroup unclickable

### ISSUE THREAD

**Issue by MarcCote** [nodeGame/nodegame-widgets#34]
I want to define a [ChoiceTableGroup](https://github.com/nodeGame/nodegame/wiki/ChoiceTableGroup-Widget-v5) where each label (i.e. text displayed in the first column) ends with a ":".

e.g.
```javascript
w.get('ChoiceTableGroup', {
                        id: 'difficulty',
                        mainText: 'How difficult did you find the games?',
                        items: [
                            "Tutorial:",
                            "Game 1:",
                            "Game 2:",
                            "Game 3:",
                        ],
                        choices: [
                            1,2,3,4,5,6,7,8,9
                        ],
                        left: 'Easiest',
                        right: 'Hardest',
                        title: false,
                        requiredChoice: 1
                    }),
```

Doing so, makes the widget unresponsive to clicks.

**Comment by MarcCote** [comment]
Also, the options `left` and `right` doesn't seem to do anything.

**Comment by shakty** [comment]
You need to specify the separator option because the default separator is "::" and it creates a conflict. It now raises an error if this is the case. Unfortunately, `left` and `right` are not supported, I updated the wiki accordingly.
