### ISSUE TITLE
"is typing" feature in chat widget possibly broken

### ISSUE THREAD

**Issue by LuxMiranda** [nodeGame/nodegame-widgets#35]
Hi,

I really like the idea of the "is typing" feature, but I'm having some problems with it.

When it shows, all I see is:
`"undefined: is typing..."
`
I can't quite figure out how to get it to display the typing player's name properly. This is how I'm constructing the widget:

```javascript
          let participantList = [];
          node.game.pl.each(function(player) {
            let playerName = playerDict[player.id]['name'];
            participantList.push(
              {
              'sender'    : player.id,
              'recipient' : player.id,
              'name'      : playerName,
              }
            );
          var chat = node.widgets.append('Chat', W.gid('chat'), {
            participants: participantList,
            docked: false,
            collapsible: false,
            closable: false,
          });
```
Further, I cannot even disable the feature. When I add `showIsTyping: false` to the constructor, the message still appears.

I would appreciate some help or some confirmation that this is a bug!

**Comment by shakty** [comment]
Hi @LuxMiranda

Really sorry I just noticed this issue only now, somehow I missed the notification. My apologies. In case this is still relevant, yes it it is a bug. I am patching it right now.

**Comment by LuxMiranda** [comment]
No worries at all! We've just downgraded the version for the time being. Take all the time you need :relaxed:

**Comment by shakty** [comment]
Thanks for your understanding!

**Comment by shakty** [comment]
This is now fixed in master. Sorry it took so long.

**Comment by LuxMiranda** [comment]
Thank you so much! No worries :heart:
